name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    uses: bertie-mc/bertie-ci/.github/workflows/build-mod.yml@v3.3.2

  publish:
    needs: build
    uses: bertie-mc/bertie-ci/.github/workflows/github-release.yml@v3.3.2
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
